/**
 * @en Standard `KeyboardEvent.key` values enum.
 * @zh 标准 `KeyboardEvent.key` 键值枚举，参考 MDN：
 *     https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values
 */
export enum Keyboard {
    // 特殊
    Unidentified = "Unidentified",

    // 修饰键（Modifier keys）
    Alt = "Alt",
    AltGraph = "AltGraph",
    CapsLock = "CapsLock",
    Control = "Control",
    Fn = "Fn",
    FnLock = "FnLock",
    Hyper = "Hyper",
    Meta = "Meta",
    NumLock = "NumLock",
    ScrollLock = "ScrollLock",
    Shift = "Shift",
    Super = "Super",
    Symbol = "Symbol",
    SymbolLock = "SymbolLock",

    // 空白类（Whitespace keys）
    Enter = "Enter",
    TabKey = "Tab",
    Space = " ",

    // 导航键（Navigation keys）
    ArrowDown = "ArrowDown",
    ArrowLeft = "ArrowLeft",
    ArrowRight = "ArrowRight",
    ArrowUp = "ArrowUp",
    End = "End",
    Home = "Home",
    PageDown = "PageDown",
    PageUp = "PageUp",

    // 编辑键（Editing keys）
    Backspace = "Backspace",
    Clear = "Clear",
    Copy = "Copy",
    CrSel = "CrSel",
    Cut = "Cut",
    Delete = "Delete",
    EraseEof = "EraseEof",
    ExSel = "ExSel",
    InsertKey = "Insert",
    Paste = "Paste",
    Redo = "Redo",
    Undo = "Undo",

    // UI keys
    Accept = "Accept",
    Again = "Again",
    Attn = "Attn",
    Cancel = "Cancel",
    ContextMenu = "ContextMenu",
    Escape = "Escape",
    Execute = "Execute",
    Find = "Find",
    Finish = "Finish",
    Help = "Help",
    Pause = "Pause",
    Play = "Play",
    Props = "Props",
    Select = "Select",
    ZoomIn = "ZoomIn",
    ZoomOut = "ZoomOut",

    // 设备键（Device keys）
    BrightnessDown = "BrightnessDown",
    BrightnessUp = "BrightnessUp",
    Eject = "Eject",
    LogOff = "LogOff",
    Power = "Power",
    PowerOff = "PowerOff",
    PrintScreen = "PrintScreen",
    Hibernate = "Hibernate",
    Standby = "Standby",
    WakeUp = "WakeUp",

    // IME / 组合键（只列部分常用）
    AllCandidates = "AllCandidates",
    Alphanumeric = "Alphanumeric",
    CodeInput = "CodeInput",
    Compose = "Compose",
    Convert = "Convert",
    Dead = "Dead",
    FinalMode = "FinalMode",
    GroupFirst = "GroupFirst",
    GroupLast = "GroupLast",
    GroupNext = "GroupNext",
    GroupPrevious = "GroupPrevious",
    ModeChange = "ModeChange",
    NonConvert = "NonConvert",
    PreviousCandidate = "PreviousCandidate",

    // 韩文键盘（Korean）
    HangulMode = "HangulMode",
    HanjaMode = "HanjaMode",
    JunjaMode = "JunjaMode",

    // 日文键盘（Japanese，仅常用）
    Eisu = "Eisu",
    Hankaku = "Hankaku",
    Hiragana = "Hiragana",
    HiraganaKatakana = "HiraganaKatakana",
    KanaMode = "KanaMode",
    KanjiMode = "KanjiMode",
    Katakana = "Katakana",
    Romaji = "Romaji",
    Zenkaku = "Zenkaku",
    ZenkakuHankaku = "ZenkakuHankaku",

    // 功能键（Function keys）
    F1 = "F1",
    F2 = "F2",
    F3 = "F3",
    F4 = "F4",
    F5 = "F5",
    F6 = "F6",
    F7 = "F7",
    F8 = "F8",
    F9 = "F9",
    F10 = "F10",
    F11 = "F11",
    F12 = "F12",
    F13 = "F13",
    F14 = "F14",
    F15 = "F15",
    F16 = "F16",
    F17 = "F17",
    F18 = "F18",
    F19 = "F19",
    F20 = "F20",
    F21 = "F21",
    F22 = "F22",
    F23 = "F23",
    F24 = "F24",

    // 字母键（Character keys）
    // 注意：KeyboardEvent.key 为实际字符，如 "a"/"A"，这里只提供方便常量
    A = "a",
    B = "b",
    C = "c",
    D = "d",
    E = "e",
    F = "f",
    G = "g",
    H = "h",
    I = "i",
    J = "j",
    K = "k",
    L = "l",
    M = "m",
    N = "n",
    O = "o",
    P = "p",
    Q = "q",
    R = "r",
    S = "s",
    T = "t",
    U = "u",
    V = "v",
    W = "w",
    X = "x",
    Y = "y",
    Z = "z",


    // 小写数字字符（主键盘）
    Digit0 = "0",
    Digit1 = "1",
    Digit2 = "2",
    Digit3 = "3",
    Digit4 = "4",
    Digit5 = "5",
    Digit6 = "6",
    Digit7 = "7",
    Digit8 = "8",
    Digit9 = "9",

    // 常用符号（取决于布局，KeyboardEvent.key 直接为字符）
    Minus = "-",
    Equal = "=",
    BracketLeft = "[",
    BracketRight = "]",
    BackslashChar = "\\",
    Semicolon = ";",
    QuoteChar = "'",
    Backquote = "`",
    Comma = ",",
    Period = ".",
    SlashChar = "/",

    // 数字键盘（Numeric keypad，使用规范中的字符值）
    Numpad0 = "0",
    Numpad1 = "1",
    Numpad2 = "2",
    Numpad3 = "3",
    Numpad4 = "4",
    Numpad5 = "5",
    Numpad6 = "6",
    Numpad7 = "7",
    Numpad8 = "8",
    Numpad9 = "9",
    NumpadAdd = "+",
    NumpadSubtract = "-",
    NumpadMultiply = "*",
    NumpadDivide = "/",
    NumpadDecimal = ".",
    NumpadSeparator = ",",

    // 媒体键（Multimedia keys，常用）
    MediaTrackNext = "MediaTrackNext",
    MediaTrackPrevious = "MediaTrackPrevious",
    MediaStop = "MediaStop",
    MediaPlay = "MediaPlay",
    MediaPause = "MediaPause",
    MediaPlayPause = "MediaPlayPause",
    MediaRecord = "MediaRecord",
    MediaRewind = "MediaRewind",
    MediaFastForward = "MediaFastForward",

    // 音量控制
    AudioVolumeUp = "AudioVolumeUp",
    AudioVolumeDown = "AudioVolumeDown",
    AudioVolumeMute = "AudioVolumeMute",
    MicrophoneToggle = "MicrophoneToggle",
    MicrophoneVolumeUp = "MicrophoneVolumeUp",
    MicrophoneVolumeDown = "MicrophoneVolumeDown",
    MicrophoneVolumeMute = "MicrophoneVolumeMute",

    // 浏览器控制键
    BrowserBack = "BrowserBack",
    BrowserFavorites = "BrowserFavorites",
    BrowserForward = "BrowserForward",
    BrowserHome = "BrowserHome",
    BrowserRefresh = "BrowserRefresh",
    BrowserSearch = "BrowserSearch",
    BrowserStop = "BrowserStop",
}
